### PR TITLE
bookings navbar link

### PR DESCRIPTION
**Pull request by allypatricio**
Moved bookings link from logged in navbar to avatar dropdown

### CODE REVIEW

**Comment by allypatricio** [comment]
screen shot 2018-05-30 at 11 47 14 pm

**Comment by sknzl** [comment]
Hey Ally, I just saw you did the same

**Comment by allypatricio** [comment]
oops! should I remove the branch?

**Comment by sknzl** [comment]
let me check, something strange happened. I'm not sure if it worked or not.

**Comment by allypatricio** [comment]
to my branch or yours? I haven't merged mine

**Comment by sknzl** [comment]
there was some delay. it's merged now what I did before. should we delete the branch that isn't merged yet?
screen shot 2018-05-30 at 23 51 41

**Comment by allypatricio** [comment]
Yea, I think so. :)

**Comment by sknzl** [comment]
I'm not sure how it is done. you have an idea? if not let's just leave it as it is for the moment.

**Comment by allypatricio** [comment]
going to give it a try

**Pull request closed without merging**
