### PR TITLE
Card design

### PR DESCRIPTION
**Pull request by allypatricio**
Have a look @ this design, still need to work on placing the text properly & need to remove that top right avatar circle.

### CODE REVIEW

**Comment by allypatricio** [comment]
screen shot 2018-05-30 at 11 04 25 am

**Comment by sknzl** [comment]
Looks really cool! Is it already showing a user-icon if no user uploaded picture is available?

**Comment by allypatricio** [comment]
@sknzl yea

**Comment by emilykburns** [comment]
like the new card design

**Pull request merged**
